[package]
name = "bomberman"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.12"
bevy_rapier2d = { version = "*", features = [ "simd-stable", "debug-render-2d" ] }

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
